name: rise-backend
services:
  loki:
    image: grafana/loki:latest
    command: ['-config.file=/etc/loki/local-config.yaml']
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    command: ['-config.file=/etc/promtail/config.yml']
    volumes:
      - ../logs:/var/log/rise-social:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3200:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    restart: unless-stopped
