server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: rise-social-backend
    static_configs:
      - targets: [localhost]
        labels:
          job: rise-social-backend
          host: localhost
          __path__: /var/log/rise-social/app.log
          service: rise-social-backend
          env: development
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            reqId: reqId
            responseTime: responseTime
            time: time
      - timestamp:
          source: time
          format: RFC3339
      - labels:
          level:
          reqId:
